// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {

    public static final double ELEVATOR_FRONT_kP = .4;
    public static final double ELEVATOR_FRONT_kI = 0;
    public static final double ELEVATOR_FRONT_kD = 30;
    public static final double ELEVATOR_FRONT_kF = .4;
    public static final double ELEVATOR_BACK_kP = .2;
    public static final double ELEVATOR_BACK_kI = 0;
    public static final double ELEVATOR_BACK_kD = 30;
    public static final double ELEVATOR_BACK_kF = 0;
    public static final double peakOutPut = .6;

    public static final double ELEVATOR_MID_PRESET_FRONT = 90000;
    public static final double ELEVATOR_MID_PRESET_BACK = -70000;
    public static final double ELEVATOR_PICKUP_PRESET_FRONT = 2000;
    public static final double ELEVATOR_PICKUP_PRESET_BACK = 10000;

    public static final double ELEVATOR_TOP_HEIGHT_PRESET = 130000;
    public static final double ELEVATOR_MID_HEIGHT_PRESET = 80000;
    public static final double ELEVATOR_LOW_HEIGHT_PRESET = 0;

    public static final double BOOM_MOTOR_KF = 0;
    public static final double BOOM_MOTOR_KD = 100;
    public static final double BOOM_MOTOR_KI = 0;
    public static final double BOOM_MOTOR_KP = .45;

    public static final int ELEVATOR_FRONT_MOTOR_ID = 5;
    public static final int ELEVATOR_BACK_MOTOR_ID = 12;

    public static final int BOOM_MOTOR_ID = 11;
    public static final Double BOOM_SPEED_IN = -.3;
    public static final Double BOOM_SPEED_OUT = .12;

    public static final double BOOM_FULL_PRESET = 25000;
    public static final double BOOM_MID_PRESET = 9000;
    public static final double BOOM_IN_PRESET = 0;

    public static final int DRIVE_L_LEAD_MOTOR_ID = 14;
    public static final int DRIVE_L_FOLLOW_MOTOR_ID = 13;
    public static final int DRIVE_R_LEAD_MOTOR_ID = 16;
    public static final int DRIVE_R_FOLLOW_MOTOR_ID = 15;


   /**
    * public static final class DriveConstants {
    *   public static final int kLeftMotor1Port = 0;
    *   public static final int kLeftMotor2Port = 1;
    *   public static final int kRightMotor1Port = 2;
    *   public static final int kRightMotor2Port = 3; 
    * }
    */ 
    
}

